export const data = [
    {
        id: 1,
        name: "e-commerce back end",
        img: "/images/e-commerce500x340.png",
        repo: "https://github.com/shelleymcq/E-Commerce-Back-End",
        deployed: false,
        description: "This back end for an e-commerce site allows a user to connect to a database, create and seed a development database, start the server, and sync the Sequelize models to MySQL database.",
        tech: "Developed with JavaScript, Node.js, Express.js, MySQL, and Sequelize.",
    },
    {
        id: 2,
        name: "project get-hapi",
        img: "/images/get-hapi500x340.png",
        repo: "https://github.com/shelleymcq/Project-getHAPI",
        deployed: true,
        link: "https://shelleymcq.github.io/Project-getHAPI/",
        description: "When a user needs a pick-me-up, they are presented with the option to either get a random pick-me-up or select from three choices. Their top choices will appear each time they return.",
        tech: "Developed with HTML, JavaScript, CSS, and three APIs.",
    },
    {
        id: 3,
        name: "toolin' around",
        img: "/images/toolin-around500x340.png",
        repo: "https://github.com/shelleymcq/Toolin-Around",
        deployed: true,
        link: "https://toolin-around.herokuapp.com/",
        description: "A community toolshed application that provides neighbors a platform to list tools they have available and to borrow tools from one another.",
        tech: "Developed with JavaScript, Node.js, Express.js, MySQL, Sequelize, Handlebars, Bcrypt, Nodemailer, and Materialize.",
    },
    {
        id: 4,
        name: "readme generator",
        img: "/images/readme500x340.png",
        repo: "https://github.com/shelleymcq/README-Generator",
        deployed: false,
        description: "This application will allow a user to create a professional README file directly from the command line.",
        tech: "Developed with node.js. The inquirer npm package is used to prompt the user for project details and then a README.md file is generated.",
    },
    {
        id: 5,
        name: "rock-paper-scissors",
        img: "/images/rps500x340.png",
        repo: "https://github.com/shelleymcq/Rock-Paper-Scissors",
        deployed: true,
        link: "https://shelleymcq.github.io/Rock-Paper-Scissors/",
        description: "The classic game played against the computer. Local storage is used to compare the user's choice to the computer's random choice to determine the winner of each round.",
        tech: "Developed with HTML and JavaScript. Additional styling created with Bulma."
    },
  ];